Aeidl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppAeidl.urls')),
]

AppAeidl/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.db import models
from AppAeidl.choices import GenderChoices, StatusChoices
from AppAeidl.utils.Validations import positive_integer_field


class Company(models.Model):
    nit = models.CharField(unique=True, validators=[positive_integer_field], max_length=10)
    name = models.CharField(unique=True, max_length=150)
    email = models.EmailField(unique=True)
    phone = models.CharField(unique=True, validators=[positive_integer_field], max_length=12)

    def __str__(self):
        return f'{self.nit} - {self.name}'


class Person(AbstractUser):
    identification = models.CharField(unique=True, max_length=10, validators=[positive_integer_field])
    gender = models.TextField(choices=GenderChoices.CHOICES, max_length=20)
    phone = models.CharField(unique=True, max_length=12, validators=[positive_integer_field])
    photo = models.ImageField(upload_to='avatars', null=True, blank=True)

    def __str__(self):
        return f'{self.identification} - {self.get_username()}'

    class Meta(AbstractUser.Meta):
        swappable = 'AppAeidl.Person'


class Entity(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f'{self.name}'


class Patient(models.Model):
    date_birth = models.DateField()
    direction = models.CharField(max_length=150)
    person = models.OneToOneField('Person', on_delete=models.CASCADE)
    entity = models.ForeignKey('Entity', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.person.identification}, {self.person.get_username()}'


class Specialty(models.Model):
    name = models.CharField(max_length=150)
    company = models.ForeignKey('Company', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        unique_together = (('name', 'company'),)


class Role(models.Model):
    name = models.CharField(max_length=100)
    company = models.ForeignKey('Company', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        unique_together = (('name', 'company'),)
        ordering = ['-pk']


class Medic(models.Model):
    role = models.ForeignKey('Role', null=True, on_delete=models.SET_NULL)
    specialty = models.ForeignKey('Specialty', null=True, on_delete=models.SET_NULL)
    person = models.OneToOneField('Person', on_delete=models.CASCADE)
    company = models.ForeignKey('Company', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.person.identification}, {self.person.get_username()}'


class Study(models.Model):
    name = models.CharField(max_length=100)
    company = models.ForeignKey('Company', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        unique_together = (('name', 'company'),)


class Exam(models.Model):
    patient = models.ForeignKey('Patient', on_delete=models.CASCADE)
    medic = models.ForeignKey('Medic', null=True, blank=True, on_delete=models.SET_NULL)
    study = models.ForeignKey('Study', null=True, on_delete=models.SET_NULL)
    date = models.DateField(auto_now_add=True, null=True)
    status = models.CharField(choices=StatusChoices.CHOICES, max_length=40)
    file = models.FileField()
    result = models.TextField(max_length=500, null=True, blank=True)

    def __str__(self):
        return f'Patient: {self.patient.person.identification}, Medic: {self.medic.person.identification}, ' \
               f'Study: {self.study.name}, Date: {self.date}'

templates/Aeidl/company.html
{% extends 'Aeidl/home.html' %}

{% block content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Company List</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                     aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Actions</div>
                    <a {% if perms.AppAeidl.add_medic %}
                    class="dropdown-item"
                {% else %}
                    class="dropdown-item disabled"
                {% endif %}
                    href="{% url "company_create" %}"><i class="far fa-calendar-plus"></i>&nbsp;New company</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not object_list %}
                <div class="alert alert-info">There are no companies available.</div>
            {% else %}
                <form class="form-signin" method="post">
                    {% csrf_token %}
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Nit</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th class="all">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.nit }}</td>
                                <td>{{ object.name }}</td>
                                <td>{{ object.email }}</td>
                                <td>{{ object.phone }}</td>
                                <td>

                                    <a{% if perms.AppAeidl.change_medic %}
                                        class="btn btn-warning btn-circle" role="button"
                                    {% else %}
                                        class="btn btn-warning btn-circle disabled" role="button"
                                    {% endif %}
                                        href="{% url "company_update" object.pk %}">
                                        <i class="far fa-edit"></i>
                                    </a>

                                    <a {% if perms.AppAeidl.delete_medic %}
                                        class="btn btn-danger btn-circle" role="button"
                                    {% else %}
                                        class="btn btn-danger btn-circle disabled" role="button"
                                    {% endif %}
                                        href="{% url "company_erase" object.pk %}">
                                        <i class="far fa-trash-alt"></i>
                                    </a>

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/Aeidl/company_create.html
{% extends 'Aeidl/home.html' %}
{% load static %}
{% block content %}
    <div class="container" style="background-image: url({% static 'image/asd.jpg' %}); width: 100%; height: 100%;">
        <div class="container" style="width: 80%; border:1px solid gray; margin-top: 2%; margin-bottom: 2%;
            background: white; padding-top: 2%; border-radius: 1%;">
            <form role="form" method="POST">
                {% csrf_token %}
                <h2 class="text-center">
                    {% if form.changed_data %}
                        Update
                    {% else %}
                        Register
                    {% endif %}
                    Company
                </h2>
                {{ form.errors }}
                <div class="row">
                    <div class="col-md-12 col-md-offset-2">
                        <div class="form-group">
                            <label class="upper"
                                   for="{{ form.nit.name }}">{{ form.nit.label }}</label>
                            {{ form.nit }}
                        </div>
                    </div>
                    <div class="col-md-12 col-md-offset-2">
                        <div class="form-group">
                            <label class="upper"
                                   for="{{ form.name.name }}">{{ form.name.label }}</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col-md-12 col-md-offset-2">
                        <div class="form-group">
                            <label class="upper"
                                   for="{{ form.email.name }}">{{ form.email.label }}</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="col-md-12 col-md-offset-2">
                        <div class="form-group">
                            <label class="upper"
                                   for="{{ form.phone.name }}">{{ form.phone.label }}</label>
                            {{ form.phone }}
                        </div>
                    </div>
                    <hr style="width:98%; border-color: black">
                    <div class="col-md-12 col-md-offset-2">
                        <div class="form-group text-center">
                            <button class="btn btn-primary text-uppercase"
                                    type="submit"><i class="fa fa-save mr-2"></i>Save
                            </button>
                            <a href="{% url 'company_list' %}" class="btn btn-danger">
                                <span class="fa fa-undo">&nbsp;Cancel</span>
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/Aeidl/entity.html
{% extends 'Aeidl/home.html' %}

{% block content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Entity List</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                     aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Actions</div>
                    <a {% if perms.AppAeidl.add_medic %}
                    class="dropdown-item"
                {% else %}
                    class="dropdown-item disabled"
                {% endif %}
                    href="{% url "entity_create" %}"><i class="far fa-calendar-plus"></i>&nbsp;New entity</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not object_list %}
                <div class="alert alert-info">There are no entities available.</div>
            {% else %}
                <form class="form-signin" method="post">
                    {% csrf_token %}
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th class="all">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.name }}</td>
                                <td>

                                    <a{% if perms.AppAeidl.change_entity %}
                                        class="btn btn-warning btn-circle" role="button"
                                    {% else %}
                                        class="btn btn-warning btn-circle disabled" role="button"
                                    {% endif %}
                                        href="{% url "entity_update" object.pk %}">
                                        <i class="far fa-edit"></i>
                                    </a>

                                    <a {% if perms.AppAeidl.delete_entity %}
                                        class="btn btn-danger btn-circle" role="button"
                                    {% else %}
                                        class="btn btn-danger btn-circle disabled" role="button"
                                    {% endif %}
                                        href="{% url "entity_erase" object.pk %}">
                                        <i class="far fa-trash-alt"></i>
                                    </a>

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/Aeidl/exam.html
{% extends 'Aeidl/home.html' %}

{% block content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Exam List</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                     aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Actions</div>
                        <a {% if perms.AppAeidl.add_medic %}
                        class="dropdown-item"
                    {% else %}
                        class="dropdown-item disabled"
                    {% endif %}
                        href="{% url "exam_create" %}"><i class="far fa-calendar-plus"></i>&nbsp;New exam</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not object_list %}
                <div class="alert alert-info">There are no exams availables.</div>
            {% else %}
                <form class="form-signin" method="post">
                    {% csrf_token %}
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Patient</th>
                                <th>Medic</th>
                                <th>Study</th>
                                <th>Date</th>
                                <th>Status</th>
                                <th>File</th>
                                <th>Result</th>
                                <th class="all">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.patient }}</td>
                                <td>{{ object.medic }}</td>
                                <td>{{ object.study }}</td>
                                <td>{{ object.date }}</td>
                                <td>{{ object.status }}</td>
                                <td>
                                    <a href="{% url "download_file" object.file.url %}">{{ object.file }}</a>
                                </td>
                                <td>{{ object.result }}</td>
                                <td>
                                    <a {% if perms.AppAeidl.change_exam %}
                                            class="btn btn-warning btn-circle" role="button"
                                        {% else %}
                                            class="btn btn-warning btn-circle disabled" role="button"
                                        {% endif %}
                                            href="{% url "exam_update" object.pk %}"><i class="far fa-edit"></i>
                                    </a>
                                    <a {% if perms.AppAeidl.delete_exam %}
                                            class="btn btn-danger btn-circle" role="button"
                                        {% else %}
                                            class="btn btn-danger btn-circle disabled" role="button"
                                        {% endif %}
                                            href="{% url "exam_erase" object.pk %}"><i class="far fa-trash-alt"></i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/Aeidl/home.html
{% extends 'base/base.html' %}
{% block content %}{% endblock %}
{% block menu_options %}
    <!-- Nav Item - Company -->
    {% if perms.AppAeidl.view_company %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'company_list' %}">
                <i class="fas fa-fw fa-user-md"></i>
                <span>Company</span>
            </a>
        </li>
    {% endif %}

    <!-- Nav Item - Personal Medico -->
    {% if perms.AppAeidl.view_medic %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'medic_list' %}">
                <i class="fas fa-fw fa-user-md"></i>
                <span>Staff Medic</span>
            </a>
        </li>
    {% endif %}

    <!-- Nav Item - Tables -->
    {% if perms.AppAeidl.view_patient %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'paciente_list' %}">
                <i class="fas fa-fw fa-table"></i>
                <span>Patient</span></a>
        </li>
    {% endif %}

    {% if perms.AppAeidl.view_entity %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'entity_list' %}">
                <i class="fas fa-fw fa-user-md"></i>
                <span>Entity</span>
            </a>
        </li>
    {% endif %}

    {% if perms.AppAeidl.view_specialty %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'specialty_list' %}">
                <i class="fas fa-fw fa-user-md"></i>
                <span>Specialty</span>
            </a>
        </li>
    {% endif %}

    {% if perms.AppAeidl.view_role %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'role_list' %}">
                <i class="fas fa-fw fa-user-md"></i>
                <span>Role</span>
            </a>
        </li>
    {% endif %}

    {% if perms.AppAeidl.view_study %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'study_list' %}">
                <i class="fas fa-fw fa-user-md"></i>
                <span>Study</span>
            </a>
        </li>
    {% endif %}

    {% if perms.AppAeidl.view_exam %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'exam_list' %}">
                <i class="fas fa-fw fa-user-md"></i>
                <span>Exam</span>
            </a>
        </li>
    {% endif %}
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
{% endblock %}

templates/Aeidl/medic.html
{% extends 'Aeidl/home.html' %}

{% block content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Staff medic List</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                     aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Actions</div>
                    <a {% if perms.AppAeidl.add_medic %}
                    class="dropdown-item"
                {% else %}
                    class="dropdown-item disabled"
                {% endif %}
                    href="{% url "medic_create" %}"><i class="far fa-calendar-plus"></i>&nbsp;New staff medic</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not object_list %}
                <div class="alert alert-info">There are no staff medic available.</div>
            {% else %}
                <form class="form-signin" method="post">
                    {% csrf_token %}
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Person</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Specialty</th>
                                <th>Company</th>
                                <th class="all">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.person }}</td>
                                <td>{{ object.person.email }}</td>
                                <td>{{ object.role }}</td>
                                <td>{{ object.specialty }}</td>
                                <td>{{ object.company }}</td>
                                <td>

                                    <a{% if perms.AppAeidl.change_medic %}
                                        class="btn btn-warning btn-circle" role="button"
                                    {% else %}
                                        class="btn btn-warning btn-circle disabled" role="button"
                                    {% endif %}
                                        href="{% url "medic_update" object.pk %}">
                                        <i class="far fa-edit"></i>
                                    </a>

                                    <a {% if perms.AppAeidl.delete_medic %}
                                        class="btn btn-danger btn-circle" role="button"
                                    {% else %}
                                        class="btn btn-danger btn-circle disabled" role="button"
                                    {% endif %}
                                        href="{% url "medic_erase" object.pk %}">
                                        <i class="far fa-trash-alt"></i>
                                    </a>

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/Aeidl/study.html
{% extends 'Aeidl/home.html' %}

{% block content %}
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Study List</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                     aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Actions</div>
                    <a {% if perms.AppAeidl.add_medic %}
                    class="dropdown-item"
                {% else %}
                    class="dropdown-item disabled"
                {% endif %}
                    href="{% url "study_create" %}"><i class="far fa-calendar-plus"></i>&nbsp;New study</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not object_list %}
                <div class="alert alert-info">There are no studies available.</div>
            {% else %}
                <form class="form-signin" method="post">
                    {% csrf_token %}
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Company</th>
                                <th class="all">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                            <tr>
                                <td>{{ object.name }}</td>
                                <td>{{ object.company }}</td>
                                <td>

                                    <a{% if perms.AppAeidl.change_specialty %}
                                        class="btn btn-warning btn-circle" role="button"
                                    {% else %}
                                        class="btn btn-warning btn-circle disabled" role="button"
                                    {% endif %}
                                        href="{% url "study_update" object.pk %}">
                                        <i class="far fa-edit"></i>
                                    </a>

                                    <a {% if perms.AppAeidl.delete_specialty %}
                                        class="btn btn-danger btn-circle" role="button"
                                    {% else %}
                                        class="btn btn-danger btn-circle disabled" role="button"
                                    {% endif %}
                                        href="{% url "study_erase" object.pk %}">
                                        <i class="far fa-trash-alt"></i>
                                    </a>

                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

{#{% block content %}#}
{#    <div class="container" style="width: 99%; border:1px solid black; margin-top: 2%; margin-bottom: 2%;#}
{#        background: white; padding-top: 1%; padding-bottom: 1%">#}
{#        <h2 class="text-center">Study</h2>#}
{#        <form class="form-signin" method="post">#}
{#            {% csrf_token %}#}
{#            <table style="width:100%" border="1" class="table-text">#}
{#                <tr class="register">#}
{#                    <th style="width:40%">Name</th>#}
{#                    <th style="width:40%">Company</th>#}
{#                    <th style="width:10%">Edit</th>#}
{#                    <th style="width:10%">Erase</th>#}
{#                </tr>#}
{#                {% for object in object_list %}#}
{#                    <tr>#}
{#                        <td>{{ object.name }}</td>#}
{#                        <td>{{ object.company }}</td>#}
{#                        <td style="text-align: center">#}
{#                            <a {% if perms.AppAeidl.change_specialty %}#}
{#                                    class="btn btn-warning active btn-sm"#}
{#                                {% else %}#}
{#                                    class="btn btn-warning active btn-sm disabled"#}
{#                                {% endif %}#}
{#                                    href="{% url "study_update" object.pk %}">Edit</a>#}
{#                        </td>#}
{#                        <td style="text-align: center">#}
{#                            <a {% if perms.AppAeidl.delete_specialty %}#}
{#                                    class="btn btn-danger active btn-sm"#}
{#                                {% else %}#}
{#                                    class="btn btn-danger active btn-sm disabled"#}
{#                                {% endif %}#}
{#                                    href="{% url "study_erase" object.pk %}">Erase</a>#}
{#                        </td>#}
{#                    </tr>#}
{#                {% endfor %}#}
{#            </table>#}
{#        </form>#}
{#        <br>#}
{#        <div class="divCenter">#}
{#            <a {% if perms.AppAeidl.add_medic %}#}
{#                    class="btn btn-success active"#}
{#                {% else %}#}
{#                    class="btn btn-success active disabled"#}
{#                {% endif %}#}
{#                    href="{% url "study_create" %}">Create</a>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}